# Generated by nixos-generate-config on this machine.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-85273f9e-3301-4324-b191-59bf0f9bc13f";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-85273f9e-3301-4324-b191-59bf0f9bc13f".device = "/dev/disk/by-uuid/85273f9e-3301-4324-b191-59bf0f9bc13f";
  boot.initrd.luks.devices."luks-31de149f-2f9a-4e48-8d28-448a5b8875b9".device = "/dev/disk/by-uuid/31de149f-2f9a-4e48-8d28-448a5b8875b9";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-85273f9e-3301-4324-b191-59bf0f9bc13f";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-85273f9e-3301-4324-b191-59bf0f9bc13f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8E8B-5A57";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-31de149f-2f9a-4e48-8d28-448a5b8875b9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
